### ISSUE TITLE
Change chat "new" messages behaviour

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2461]
If OpenSlides is opened in several tabs (Tab A and Tab B) and the chat has a new message the new message is displayed as new in all tabs. If the message is viewed in tab A, tab B does not update the chat and still displays the messages as new. 

**Wanted behaviour:**
If the message is viewed in one tab every other open tab should then stop displaying the message as new

**Comment by jsangmeister** [comment]
I would favor a client-side solution. Would this be possible e.g. via local storage or the shared worker? @bastianjoel you had some ideas here, could you elaborate them here?

**Comment by bastianjoel** [comment]
I don't think utilizing the shared worker is needed for that. I would suggest using the [storage event](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event) or a [broadcast channel](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API).

**Comment by rrenkert** [comment]
See #2618 for other chat related bugs.

**Comment by jsangmeister** [comment]
As discussed, we want a server-side solution for this, as the client-only solution proved to be not powerful enough.

Proposal for the required changes: We introduce a new model `last_read_message` (or some other name) with the following fields:
```
last_read_message:
  id:
    type: number
    constant: true
  meeting_user_id:
    type: relation
    to: meeting_user/last_read_message_ids
    required: true
    constant: true
  chat_group_id:
    type: relation
    to: chat_group/last_read_message_ids
    required: true
    constant: true
  message_id:
    type: relation
    to: chat_message/last_read_message_ids
    required: true
  meeting_id:
    type: relation
    to: meeting/last_read_message_ids
    required: true
    constant: true
```
(and additional reverse relations)

For each meeting user and chat group, such a model is created as soon as the chat group is opened for the first time if at least one message exists for this group. The most recent chat message is used as the `message_id`. Whenever a new message arrives in an open chat group or a chat group is opened with new messages, the respective `last_read_message` model for this user and group is updated with the most recent `message_id`.

The new collection has the following "can see" restriction: A user can see the model if the linked meeting user belongs to them. This means that the reverse relations are automatically filtered so that a user only receives this model for himself and not for other users. The client can then use this information to display the information in the same way it currently does (currently, the "last read message" is simply saved into local storage per chat group). Therefore, little work should be required in the client to implement this solution.

The backend will need an additional action `chat_group.set_last_read_message`, which takes a `chat_group_id` as well as a `chat_message_id` and creates or updates the respective `last_read_message` model for the combination of request user and chat group. Additionally, when a chat message is created, the backend should update the last read message for the request user and the group of the message to the newly created message. No other backend changes should be necessary.
