### ISSUE TITLE
Improve SAML options in superadmin settings

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-client#2944]
At the moment the following (here relevant) SAML related fields are defined:
```yaml
  # Saml settings 
  # [...]                                                         
  saml_metadata_idp:                                 
    type: text                                                      
    restriction_mode: A                                                          
  saml_metadata_sp:                       
    type: text                                                   
    restriction_mode: A                                                                                                                                                                                             
  saml_private_key:                                                                                                                                                                                                 
    type: text                                                                                                                                                                                                      
    restriction_mode: A           
```

As far as I know these are set with a simple `organization.update` action issued by the client. This requires the end user to do much work which can be automated, which would make the SAML setup much more robust.

The following steps must be completed by the end user:
1. find the metadata of the IdP and copy-paste as xml
2. generate a x509 key pair
3. Manually write/generate a metadata xml definition for the SP (OpenSlides) and fiddle the public key from 2. and other redundant information (such as URL) into it
4. Paste the private key and and SP-metadata making sure no weird formatting or white space errors occur

IMO this should be vastly reduced to
1. Provide the metadata URL of the IdP (from where the xml can be downloaded)
2. Click a button to generate the x509 key pair, as well as the appropriate metadata containing the public key and all other relevant info
-> This should also be re doable in order to invalidate an existing key pair and use a newly generated one

Most of the work to realize this must be done in the backend - at least the way I see it right now.
However the client will also change the interface and the actions to call.

So this issue should be tackled once the steps https://github.com/OpenSlides/openslides-backend/issues/1933 are clear / confirmed.
Then the TODOs for the client can probably also be defined more specifically.
